//! Rust driver for the C test corpus.
//!
//! The tests themselves are C, in `c_test/src/tests/`, and are shared with the
//! CTest driver — this package only provides a second way to run them, so that
//! `cargo test` is a complete verification path with no CMake step.
//!
//! Granularity is per group rather than per test: Unity's `TEST()` macro emits
//! a `static` function, but `TEST_GROUP_RUNNER()` emits an externally linkable
//! `RunTestGroup_*`, which is what `sr_run_test_group` dispatches to.

/// Keeps `surrealdb_c` in the link graph so the C objects can resolve the
/// `sr_*` symbols they call.
#[doc(hidden)]
pub fn link_anchor() -> usize {
    surrealdb_c::Surreal::connect as usize
}

#[cfg(test)]
mod tests {
    use std::ffi::CString;
    use std::os::raw::{c_char, c_int};
    use std::sync::Mutex;

    extern "C" {
        /// Runs one Unity group and returns the number of failed assertions.
        fn sr_run_test_group(group: *const c_char) -> c_int;
    }

    /// Unity accumulates results in globals and is not thread safe, so the
    /// groups run one at a time. The whole corpus takes seconds, so there is
    /// nothing to gain from running them concurrently.
    static UNITY: Mutex<()> = Mutex::new(());

    fn run_group(group: &str) {
        // A panic in one group poisons the lock; the remaining groups should
        // still report their own results rather than cascade.
        let _guard = UNITY.lock().unwrap_or_else(|poisoned| poisoned.into_inner());

        super::link_anchor();

        let name = CString::new(group).expect("group name");
        let failures = unsafe { sr_run_test_group(name.as_ptr()) };

        assert_eq!(failures, 0, "{group}: {failures} failing test(s)");
    }

    macro_rules! test_group {
        ($name:ident, $group:literal) => {
            #[test]
            fn $name() {
                run_group($group);
            }
        };
    }

    // One #[test] per Unity group, generated by build.rs from the corpus.
    include!(concat!(env!("OUT_DIR"), "/groups.rs"));
}

/// The C examples, each run as a test.
///
/// They are complete programs; build.rs renames their `main` and generates a
/// #[test] per file. An example that stops compiling or starts failing breaks
/// `cargo test`, which CMake-only builds did not.
#[cfg(test)]
mod examples {
    include!(concat!(env!("OUT_DIR"), "/examples.rs"));
}

/// The generated header is part of the public contract, so a few properties of
/// it are asserted directly rather than left to review.
#[cfg(test)]
mod header_contract {
    fn header() -> String {
        // The header sits next to the crate that generates it.
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../include/surrealdb.h");
        std::fs::read_to_string(path).expect("include/surrealdb.h should exist")
    }

    /// Every identifier the header exports must carry the `SR_`/`sr_` prefix.
    ///
    /// This exists because four enum constants did not: `sr_credentials_scope`
    /// spelled its variants `ROOT`, `NAMESPACE`, `DATABASE` and `RECORD`, the
    /// only four of 52 without a prefix. Two of them already collide with
    /// macros in clang's own headers, and the header is included by every
    /// consumer translation unit -- this library is header-only on the C++
    /// side, so there is nowhere for such a name to hide.
    #[test]
    fn every_enum_constant_is_prefixed() {
        let src = header();
        let mut offenders: Vec<String> = Vec::new();
        let mut depth = 0usize;

        for line in src.lines() {
            let t = line.trim();
            if t.starts_with("typedef enum") {
                depth = 1;
                continue;
            }
            if depth == 0 {
                continue;
            }
            if t.starts_with('}') {
                depth = 0;
                continue;
            }
            if t.starts_with("/*") || t.starts_with('*') || t.starts_with("//") || t.is_empty() {
                continue;
            }
            let name: String = t
                .trim_end_matches(',')
                .split(|c: char| c == '=' || c.is_whitespace())
                .next()
                .unwrap_or("")
                .to_string();
            if name.is_empty() {
                continue;
            }
            if !name.starts_with("SR_") && !name.starts_with("sr_") {
                offenders.push(name);
            }
        }

        assert!(
            offenders.is_empty(),
            "unprefixed enum constants in the public header: {offenders:?}\n\
             Every exported name needs an SR_ prefix; these would collide with \
             whatever the consumer already has."
        );
    }

    /// No exported type name may collide with an exported enum constant.
    ///
    /// In C both live in the ordinary identifier namespace, so a typedef and an
    /// enumerator that share a name is a redefinition error in every consumer.
    /// This is not hypothetical: the geometry structs were `sr_sr_g_point` and
    /// friends, double-prefixed by cbindgen, and the *only* reason that
    /// compiled was that the tag enum's variants had taken `sr_g_point`.
    /// Correcting the prefix collided immediately.
    #[test]
    fn no_type_name_collides_with_an_enum_constant() {
        let src = header();
        let mut typedefs: Vec<String> = Vec::new();
        for line in src.lines() {
            let t = line.trim();
            if let Some(rest) = t.strip_prefix("} ") {
                if let Some(name) = rest.strip_suffix(';') {
                    if !name.is_empty() {
                        typedefs.push(name.to_string());
                    }
                }
            }
        }

        let mut constants: Vec<String> = Vec::new();
        let mut depth = 0usize;
        for line in src.lines() {
            let t = line.trim();
            if t.starts_with("typedef enum") { depth = 1; continue; }
            if depth == 0 { continue; }
            if t.starts_with('}') { depth = 0; continue; }
            if t.starts_with("/*") || t.starts_with('*') || t.starts_with("//") || t.is_empty() {
                continue;
            }
            let name: String = t
                .trim_end_matches(',')
                .split(|c: char| c == '=' || c.is_whitespace())
                .next().unwrap_or("").to_string();
            if !name.is_empty() { constants.push(name); }
        }

        let clashes: Vec<&String> =
            typedefs.iter().filter(|t| constants.contains(t)).collect();
        assert!(
            clashes.is_empty(),
            "type names that are also enum constants: {clashes:?}\n\
             C puts both in one namespace, so this will not compile downstream."
        );
    }

    /// The status codes the docs refer to must actually be defined, and with
    /// the unprefixed spelling the rest of the header uses in prose.
    #[test]
    fn status_codes_are_defined() {
        let src = header();
        for m in ["SR_NONE", "SR_CLOSED", "SR_ERROR", "SR_FATAL"] {
            assert!(
                src.contains(&format!("#define {m} ")),
                "{m} should be defined in the header"
            );
        }
        // cbindgen's export.prefix stacks onto names that already begin with
        // sr_, which is how sr_SR_ERROR and sr_sr_toggle_t both happened.
        assert!(!src.contains("sr_SR_"), "double-prefixed constant in the header");
        assert!(!src.contains("sr_sr_"), "double-prefixed type in the header");
    }
}
